// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgenciaViagemTrabalho.Models
{
    [Index(nameof(Cpf), Name = "IX_Cliente", IsUnique = true)]
    [Index(nameof(Email), Name = "IX_Email", IsUnique = true)]
    public partial class Cliente
    {
        public Cliente()
        {
            PassagemClienteVenda = new HashSet<PassagemClienteVenda>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [Column("cpf")]
        [StringLength(50)]
        public string Cpf { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(50)]
        public string Senha { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<PassagemClienteVenda> PassagemClienteVenda { get; set; }
    }
}