// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgenciaViagemTrabalho.Models
{
    [Table("Passagem_Cliente_Venda")]
    public partial class PassagemClienteVenda
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("id_Cliente")]
        public int IdCliente { get; set; }
        [Column("id_Passagem")]
        public int IdPassagem { get; set; }
        [Column("preco", TypeName = "decimal(18, 0)")]
        public decimal Preco { get; set; }
        [Column("data_compra", TypeName = "datetime")]
        public DateTime DataCompra { get; set; }

        [ForeignKey(nameof(IdCliente))]
        [InverseProperty(nameof(Cliente.PassagemClienteVenda))]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey(nameof(IdPassagem))]
        [InverseProperty(nameof(Passagem.PassagemClienteVenda))]
        public virtual Passagem IdPassagemNavigation { get; set; }
    }
}