// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgenciaViagemTrabalho.Models
{
    public partial class Passagem
    {
        public Passagem()
        {
            PassagemClienteVenda = new HashSet<PassagemClienteVenda>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("embarque")]
        [StringLength(50)]
        public string Embarque { get; set; }
        [Required]
        [Column("destino")]
        [StringLength(50)]
        public string Destino { get; set; }
        [Column("acompanhantes")]
        public int Acompanhantes { get; set; }
        [Column("ida", TypeName = "datetime")]
        public DateTime Ida { get; set; }
        [Column("volta", TypeName = "datetime")]
        public DateTime Volta { get; set; }

        [InverseProperty("IdPassagemNavigation")]
        public virtual ICollection<PassagemClienteVenda> PassagemClienteVenda { get; set; }
    }
}